-- =============================================================
-- 장바구니 풀스택 - Supabase 스키마 & 시드
-- Supabase 대시보드 > SQL Editor 에 붙여넣어 실행하세요.
-- (스키마 생성 → 시드 → 시퀀스 보정 순서)
-- =============================================================

-- ----------------------------------------------------------------
-- 1. 테이블
-- ----------------------------------------------------------------

create table if not exists products (
  id        bigint generated by default as identity primary key,
  name      text   not null unique,
  price     bigint not null check (price > 0),   -- 큰 금액(1e11)을 위해 bigint
  image_url text   not null
);

create table if not exists cart_items (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  quantity   int    not null check (quantity between 1 and 99)
);

create table if not exists coupons (
  id              bigint generated by default as identity primary key,
  name            text   not null,
  type            text   not null,            -- FIXED5000 | BOGO | FREESHIPPING | MIRACLESALE
  expiration_date date   not null
  -- 할인 금액/비율/최소주문금액 등 '할인 정책'은 type 으로 결정되며,
  -- step4 계산 로직에서 type 별 상수로 관리한다. (DB 는 카탈로그만 보관)
);

-- ----------------------------------------------------------------
-- 2. RLS
--    서버가 anon key 로 직접 접근하므로, 학습용으로 RLS 를 끕니다.
--    (운영에서는 service_role 키 사용 또는 정책(policy) 설정을 권장)
-- ----------------------------------------------------------------

alter table products   disable row level security;
alter table cart_items disable row level security;
alter table coupons    disable row level security;

-- ----------------------------------------------------------------
-- 3. 시드 데이터 (id 명시 삽입)
-- ----------------------------------------------------------------

insert into products (id, name, price, image_url) values
  (1, 'EASTER',   100000000000, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop'),
  (2, 'PARADI',   1,            'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=200&h=200&fit=crop'),
  (3, 'BIBIBING', 2000,         'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&h=200&fit=crop'),
  (4, 'ZO',       20000000,     'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=200&h=200&fit=crop'),
  (5, '6month',   2,            'https://images.unsplash.com/photo-1495707902641-75cac588d2e9?w=200&h=200&fit=crop')
on conflict (id) do nothing;

insert into cart_items (id, product_id, quantity) values
  (1, 1, 1),
  (2, 2, 2),
  (3, 5, 98)
on conflict (id) do nothing;

insert into coupons (id, name, type, expiration_date) values
  (1, '5,000원 할인 쿠폰',     'FIXED5000',    '2026-11-30'),
  (2, '2+1 쿠폰',             'BOGO',         '2026-06-30'),
  (3, '무료 배송 쿠폰',        'FREESHIPPING', '2026-08-31'),
  (4, '30% 시간제 할인 쿠폰',  'MIRACLESALE',  '2026-07-31')
on conflict (id) do nothing;

-- ----------------------------------------------------------------
-- 4. 시퀀스 보정
--    id 를 명시 삽입했으므로, 다음 자동 증가 값이 충돌하지 않도록 맞춥니다.
-- ----------------------------------------------------------------

select setval(pg_get_serial_sequence('products',   'id'), (select max(id) from products));
select setval(pg_get_serial_sequence('cart_items', 'id'), (select max(id) from cart_items));
select setval(pg_get_serial_sequence('coupons',    'id'), (select max(id) from coupons));
