begin;

do $$
declare
  suffix text := to_char(clock_timestamp(), 'YYYYMMDDHH24MISS');
begin
  if to_regclass('public."Cart"') is not null then
    execute format('alter table public."Cart" rename to %I', 'Cart_legacy_' || suffix);
  end if;

  if to_regclass('public."Coupon"') is not null then
    execute format('alter table public."Coupon" rename to %I', 'Coupon_legacy_' || suffix);
  end if;

  if to_regclass('public."Product"') is not null then
    execute format('alter table public."Product" rename to %I', 'Product_legacy_' || suffix);
  end if;
end $$;

create table public."Product" (
  id integer generated by default as identity primary key,
  name text not null,
  price integer not null check (price > 0),
  "imgUrl" text
);

create table public."Cart" (
  "productId" integer primary key references public."Product"(id) on delete cascade,
  quantity integer not null check (quantity between 1 and 99)
);

create table public."Coupon" (
  id integer generated by default as identity primary key,
  code text not null unique,
  description text not null,
  "expirationDate" date not null,
  "discountType" text not null check (
    "discountType" in ('fixed', 'bogo', 'freeShipping', 'percentage')
  ),
  "discountAmount" integer,
  "minimumAmount" integer,
  "buyQuantity" integer,
  "getQuantity" integer,
  "discountRate" integer,
  "availableTime" jsonb
);

insert into public."Product" (id, name, price, "imgUrl") values
  (1, '상품 A', 10000, 'https://placehold.co/200x200/png?text=A'),
  (2, '상품 B', 25000, 'https://placehold.co/200x200/png?text=B'),
  (3, '상품 C', 23000, 'https://placehold.co/200x200/png?text=C'),
  (4, '상품 D', 42000, 'https://placehold.co/200x200/png?text=D');

select setval(
  pg_get_serial_sequence('public."Product"', 'id'),
  (select max(id) from public."Product")
);

insert into public."Cart" ("productId", quantity) values
  (1, 2),
  (2, 1);

insert into public."Coupon" (
  id,
  code,
  description,
  "expirationDate",
  "discountType",
  "discountAmount",
  "minimumAmount",
  "buyQuantity",
  "getQuantity",
  "discountRate",
  "availableTime"
) values
  (
    1,
    'FIXED5000',
    '5,000원 할인 쿠폰',
    '2026-11-30',
    'fixed',
    5000,
    100000,
    null,
    null,
    null,
    null
  ),
  (
    2,
    'BOGO',
    '2+1 쿠폰',
    '2026-06-30',
    'bogo',
    null,
    null,
    2,
    1,
    null,
    null
  ),
  (
    3,
    'FREESHIPPING',
    '무료 배송 쿠폰',
    '2026-08-31',
    'freeShipping',
    null,
    50000,
    null,
    null,
    null,
    null
  ),
  (
    4,
    'MIRACLESALE',
    '30% 시간제 할인 쿠폰',
    '2026-07-31',
    'percentage',
    null,
    null,
    null,
    null,
    30,
    '{"start":"04:00","end":"07:00"}'::jsonb
  );

select setval(
  pg_get_serial_sequence('public."Coupon"', 'id'),
  (select max(id) from public."Coupon")
);

commit;
