// 도메인/애플리케이션 전반에서 쓰는 에러 코드의 단일 출처.
// 새 코드를 추가하면 STATUS_BY_CODE 매핑이 누락될 때 컴파일 에러가 발생한다.
export type ErrorCode =
  | 'INVALID_PRODUCT_NAME'
  | 'INVALID_PRODUCT_PRICE'
  | 'INVALID_REMAINING_QUANTITY'
  | 'INVALID_IMAGE_URL'
  | 'INVALID_PRODUCT_ID'
  | 'INVALID_PURCHASE_QUANTITY'
  | 'INVALID_CART_ITEM_ID'
  | 'INVALID_CART_ITEM_IDS'
  | 'INVALID_COUPON_IDS'
  | 'INVALID_IS_REMOTE_AREA'
  | 'EXCEEDS_REMAINING_QUANTITY'
  | 'EXCEEDS_COUPON_LIMIT'
  | 'PRODUCT_NOT_FOUND'
  | 'CART_ITEM_NOT_FOUND'
  | 'COUPON_NOT_FOUND'
  | 'COUPON_EXPIRED'
  | 'COUPON_ALREADY_USED'
  | 'COUPON_NOT_APPLICABLE';

// 에러 코드 → HTTP 상태코드 매핑. Record로 강제하므로 코드 누락 시 컴파일 에러.
export const STATUS_BY_CODE: Record<ErrorCode, number> = {
  INVALID_PRODUCT_NAME: 400,
  INVALID_PRODUCT_PRICE: 400,
  INVALID_REMAINING_QUANTITY: 400,
  INVALID_IMAGE_URL: 400,
  INVALID_PRODUCT_ID: 400,
  INVALID_PURCHASE_QUANTITY: 400,
  INVALID_CART_ITEM_ID: 400,
  INVALID_CART_ITEM_IDS: 400,
  INVALID_COUPON_IDS: 400,
  INVALID_IS_REMOTE_AREA: 400,
  EXCEEDS_REMAINING_QUANTITY: 400,
  EXCEEDS_COUPON_LIMIT: 400,
  PRODUCT_NOT_FOUND: 404,
  CART_ITEM_NOT_FOUND: 404,
  COUPON_NOT_FOUND: 404,
  COUPON_EXPIRED: 400,
  COUPON_ALREADY_USED: 400,
  COUPON_NOT_APPLICABLE: 400,
};
